remote_theme : thelehhman/texture
title: like a diary
author: Unice Heo
email: heunb94@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  여러가지
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Unice Heo
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false
  disqus_shortname: various studies
  showNav: false
  navigation:
    - title: JavaScript
      url: "/javascript"
  # generate social links in footer
  social_links:
    github:  UniceHeo

 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
